### ISSUE TITLE
Mobile Navigation

### ISSUE THREAD

**Issue by ezekeal** [survivejs/webpack-book#203]
The "need help?" Button covers up the next page nav on mobile
http://imgur.com/DRFZ94R

**Comment by bebraw** [comment]
Good call. I wonder what's the right fix. I could just hide the button on low res. Does that make sense to you?

**Comment by bebraw** [comment]
This should be fixed now. I ended up hiding it on low resolution. Looks like Chrome needs a hard refresh (cmd-shift-r) to pick it up.

Thanks for the report. Please open separate issues if/when you find annoying things. 👍
