### ISSUE TITLE
Eliminating Unused CSS - pure-button doesn't work with h1 element

### ISSUE THREAD

**Issue by ithinco** [survivejs/webpack-book#206]
pure-button class doesn't apply its styles on h1 element. When I changed the element from h1 to button, it works as expected.

Chrome Version 56.0.2924.87 (64-bit)
"purecss": "^0.6.2"

**Comment by bebraw** [comment]
Can you link to a minimal project to study? I'm curious to understand why that happens.

**Comment by bebraw** [comment]
Ah, pure.css, not purify... Can you report this upstream to https://github.com/yahoo/pure/ ? That's the right place for this. 👍

**Comment by ithinco** [comment]
Nope, PureCSS doc never said that you should use pure-button on h1 element.  It is for the clarity of this book that I reported this issue.:)

**Comment by bebraw** [comment]
Ah... Good point. I'll add a note.

You may still want to report the issue upstream so they'll get it fixed. 👍

**Comment by bebraw** [comment]
I think I'll change the element to `div` to play it safe. Thanks for the heads up.
