### ISSUE TITLE
Chinese translation application

### ISSUE THREAD

**Issue by BingBlog** [survivejs/webpack-book#223]
I was read SurviveJS-webpack on the Internet last year, I think this book is very good. And then I started translating the book to Chinese blog. I would like to know whether I can share the translated blog with my workmate, or put on the network. Thank you!

**Comment by bebraw** [comment]
Hi,

I have a little official translation effort going on. The idea would be to get an actual translated book out. I poked the guys to see what they think. I'll get back to you on this. 👍

**Comment by BingBlog** [comment]
That great! I talked this thing to one of my workmate, he is also very interested. His English is better then me and passed TOEFL a few year ago. he also used WebPack well in our develops, I think we work together to translate the book is a good idea. Waiting your message.
PS: Here is the url of translations of earlier edition on GitHub pages: https://bingblog.github.io/tags/SurviveJs/page/3/

**Comment by BingBlog** [comment]
I think I'm wrong. If you have already started to translate. I am glad to wait for the Chinese version of the book.

**Comment by bebraw** [comment]
Hi,

I'll let you know when I know more. Possibly we can do some sort of joint effort. 👍

**Comment by BingBlog** [comment]
Okay, we'll wait for your reply.

**Comment by bebraw** [comment]
Hi,

I haven't heard back from the guys yet. But if we proceed, I think we could do it like with the Spanish translation. The process would go like this:

1. I would set up a repository below `survivejs-translations` org. You would be free to work there as you like.
2. I would set up a site that syncs with that. Most likely we'll get `zh.survivejs.com` to match the country code. The idea is that you can access the content through it.
3. To give access to pdf/epub/mobi, I would "sell" the book for $0 through Leanpub. If someone wants to pay, that's still possible. We would have to agree on what to do with the possible earnings (push to Open Collective to distribute?). Other distribution (Amazon, Chinese, etc.) needs thought as well.

I hope to have more info in a few days.

**Comment by BingBlog** [comment]
Hi,
We are OK with all you suggestion. We make some change to make it better:
1、 We will work at the repository you set up below ```survivejs-translations```
2、Due to the network limitation in China, most people don't has access to```www.survivejs.com```, so they can't access the content through ```cn.survivejs.com```, We suggest with the ```www.survivejs.cn```which I just registered. 
3、We are OK with the idea of Leanpub. If our Chinese translation will be published. I think that will take some time. If that happens, we can discuss it in detail at that time. Maybe you don't know: Chinese books are cheaper  than English books. Get paid is not the main reason We translate the book.

**Comment by bebraw** [comment]
@BingBlog A couple of comments below (still haven't heard back from the translators).

> 1、 We will work at the repository you set up below survivejs-translations

Ok.

> 2、Due to the network limitation in China, most people don't has access towww.survivejs.com, so they can't access the content through cn.survivejs.com, We suggest with the www.survivejs.cnwhich I just registered.

Would it be possible to move the domain below my company? That way I can ensure it will stay up and running. Seems safer. 👍 

> 3、We are OK with the idea of Leanpub. If our Chinese translation will be published. I think that will take some time. If that happens, we can discuss it in detail at that time. Maybe you don't know: Chinese books are cheaper than English books. Get paid is not the main reason We translate the book.

Yeah. This is why I feel selling for zero is the way. But I agree this is a harder topic we can revisit.

**Comment by BingBlog** [comment]
We are OK with your suggestion. The ```www.survivejs.cn``` is  registered at ```www.aliyun.com```. According to aliyun‘s rules, it will take four days for it to be allowed to trade, and it will take another two months to be allowed moved out from aliyun. If you think this is OK, I will sell you for zero. If you feel trouble, we can use cn.survivejs.com. But network speed will be affected. I have confirmed with my friends, if the domain name is not limited by government, is accessible. Anyway, I will move the domain to you. I think use ```www.survivejs.cn``` with a new server at china will be the best choose. It just my suggestion, We just want to make the book read by more people.

**Comment by bebraw** [comment]
@bjrmatos Ok, sounds fair. Good point on server too. I am not so familiar with government restrictions. 👍 

There's [a repo](https://github.com/survivejs-translations/webpack-book-zh) now.

I think the basic infrastructure should be in place. We can continue on that repo under specific issues to get more bits set up as needed.

Thanks.

**Comment by BingBlog** [comment]
OK, we will start the translate work. Specific issues will be discussed on that repo.
