### ISSUE TITLE
Spelling Error?

### ISSUE THREAD

**Issue by eryue0220** [survivejs/webpack-book#253]
In the optimizing chapter optimize [minifying](https://github.com/survivejs/webpack-book/blob/dev/manuscript/optimizing/01_minifying.md) The `Conclusion`part. I think this sentence `it can be less performant that UglifyJS.` should be `it can be less performant "than" UglifyJS.` right? I am not a native English, so I am not sure it is a spelling error or not. If it is not, please omit.

**Comment by bebraw** [comment]
Yeah, I'll fix that. Good call.
