### ISSUE TITLE
Optimizing - useSourceMap: true passed to minifyJavaScript

### ISSUE THREAD

**Issue by jasonreed7** [survivejs/webpack-book#266]
Hi,
I'm going through the book and noticed that in the code for webpack.config.js in optimizing- minifying css, {useSourceMap: true}  is passed to parts.minifyJavaScript, and is not in the minifying javascript section. I saw this sentence in the minifying javascript section as well- "The plugin exposes more functionality, but having the possibility of toggling source maps is enough." so I wonder if it was meant to be included.
Thanks for the great book!

**Comment by bebraw** [comment]
Thanks, good call. I'll alter that a bit.
