### ISSUE TITLE
Error with path component in the index.js page 6

### ISSUE THREAD

**Issue by wirtaw** [survivejs/webpack-book#271]
When try make bundle with ``node_modules/.bin/webpack``
``
ERROR in ./app/index.js
Module not found: Error: Can't resolve './component' in 'xxxxxxxx/webpack-demo/app'
 @ ./app/index.js 1:0-36
``
get error
If add to import directory at index.js
``
from './component/component.js'
``
then it make bundle without errors

**Comment by bebraw** [comment]
Hi,

Can you push a project showing the issue to GitHub? It's easier to debug then.

**Comment by wirtaw** [comment]
Hi,
Yes, I can. Where is 
[webpack-demo](https://github.com/wirtaw/webpack-demo)

**Comment by bebraw** [comment]
Hi,

Alter the `app` directory so that it looks like this:

```bash
app $ tree
.
├── component.js
└── index.js
```

That will fix the import.

**Comment by wirtaw** [comment]
Yes, it also helps. 
Thank you!

**Comment by bebraw** [comment]
No probs. I'm not sure if you noticed but I have a sort of summary of the content online in form of [slides](http://presentations.survivejs.com/webpack-from-apprentice-to-journeyman/). Maybe that helps. We also have a little [chat](https://gitter.im/survivejs/webpack).
