### ISSUE TITLE
Better to mention to disable the autoprefixer of the cssnano

### ISSUE THREAD

**Issue by shuaibird** [survivejs/webpack-book#274]
Section: Optimizing - Minifying - Minifying Css
By default, the cssnano would remove the vendor prefix of the stylesheet. So I think it better to disable the autoprefixer, or at least inform the reader somewhere in this section.

**Comment by bebraw** [comment]
Yeah, good point. That should become a warning.

**Comment by sapegin** [comment]
As I see in the docs it’s disabled by default: http://cssnano.co/guides/optimisations/

> By default, the cssnano would remove the vendor prefix of the stylesheet.

This is not correct: it will remove only unnecessary prefixes based on your browserslist, if this option is enabled.

**Comment by shuaibird** [comment]
@sapegin Nope. Here's my `.broswerslistrc` file, you could test it by using the `flex`.
```
ios >= 8
android > 4.4
and_qq > 9
```

**Comment by sapegin** [comment]
Then the cssnano docs are wrong, feel free to send a pull request there ;-)

**Comment by shadowz10** [comment]
@sapegin Hello, I would like to translate to Spanish but I do not know how. I would like to do it by means of pull request :)

**Comment by bebraw** [comment]
@shadowz10 I set up a [repository](https://github.com/survivejs-translations/webpack-book-es) for you. You could translate against the master branch. Let me know if you need help syncing the work etc. I can also get it online when you want.

**Comment by shadowz10** [comment]
@bebraw perfect, I can do the translations using PR?

**Comment by bebraw** [comment]
@shadowz10 You could write PRs, have someone review, and then merge to `master` over there, yeah. You could ask @raulexposito how he did it.

**Comment by shadowz10** [comment]
@bebraw thanks, I'm already working on some translations when you can review them to merge them.

**Comment by bebraw** [comment]
@shuaibird @sapegin Is this relevant still? Is there something to change here?

**Comment by bebraw** [comment]
Let's close.
