### ISSUE TITLE
Loading JavaScript - clean the babel cache before building the production release

### ISSUE THREAD

**Issue by shuaibird** [survivejs/webpack-book#275]
Enabling the `cacheDirectory` of the `babel-loader` sometimes could lead to problems: you may write some code before installing the plugin for transpiling, these code would not be transpiled after the plugin is installed later as long they're already cached by the `babel-loader`. I think being unaware of this may end up with frustration.

**Comment by bebraw** [comment]
Yeah, good point. I think this is going to need a warning and/or better caching method (nicer way to  calculate the hash).

**Comment by rafde** [comment]
Would encouraging the use of `cache-loader` instead of babel's `cacheDirectory` be a better direction?

**Comment by bebraw** [comment]
@rafde Yeah, that's smart. 👍

**Comment by bebraw** [comment]
There's `cache-loader` in the book now. I also dropped caching from the Babel bit as it's a little simpler that way. Thanks for the input.

**Comment by Andrey-Bushman** [comment]
> There's `cache-loader` in the book now. I also dropped caching from the Babel bit as it's a little simpler that way. Thanks for the input.

I bought the book and I see `cacheDirectory` instead of `cache-loader` still (in the *Setting Up babel-loader*).

**Comment by bebraw** [comment]
@Andrey-Bushman Send me email and I'll give you access to the Leanpub edition since you paid for the Amazon one. It's trickier to push releases to Amazon as then it's a full edition and I didn't have time to push the webpack 4 version of the book out there last year due to other work.

**Comment by bebraw** [comment]
Looks like **babel-loader** implements `cacheDirectory` still so that direction should be valid still. The **cache-loader** technique is more generic and can be applied with any loader.
