### ISSUE TITLE
Better explanation of different configuration ways

### ISSUE THREAD

**Issue by rylphs** [survivejs/webpack-book#278]
Hello,
I am reading the book and finding it very, very helpfull. However I am a little bit confuse about different ways to configure webpack. For example:

```javascript
const commonConfig = merge([{
        entry: {...  },
        output: {... },
        plugins: [ //plugin set up in the main plugins section
            new HtmlWebpackPlugin({
                title: 'Webpack HelloWorld'
            })
        ]
    } ]);

exports.extractCss = ({ include, exclude, use }) => {
    const plugin = new ExtractTextPlugin({filename: '[name].css'});
    return { 
        module: {
            rules: [{
                    test: /\.(css|scss)$/,
                    include, exclude,
                     //plugin in the main plugins section, plus function helper ??
                    use: plugin.extract({ 
                        use, fallback: 'style-loader'
                    })
                } ]
        },
        plugins: [plugin]
    }
};

exports.autoPrefix = ()=> ({
    loader: 'postcss-loader',
    options: {
        plugins: ()=> ([ //plugin as a function in the loader options
            require('autoprefixer')()
        ])
    }
})
```
It seems that sometimes is just enough to set a new plugin at plugins section. Sometimes you have to call a plugin method anywhere in the code and sometimes you have to declare a plugin in the options section of a loader. I don't know if is just me, but I would like so much if the book had a brief explanation of that.

**Comment by bebraw** [comment]
Hi,

It's a bit arbitrary, yup. You can wrap everything within a function if you like. It's means of organization for me. I find it particularly useful for `extractCss` as it allows me to group related concerns (plugin and loader) together. Otherwise that coupling would be harder to understand.

**Comment by bebraw** [comment]
There's an entire chapter about the topic now. See https://survivejs.com/webpack/developing/composing-configuration/ .
