### ISSUE TITLE
chapter Techniques/testing: Configuration file found but no entry configured.

### ISSUE THREAD

**Issue by Aladdin-ADD** [survivejs/webpack-book#279]
thanks for the amazing work! it helped me a a lot!

in `Techniques => testing => Configuring Webpack`, when running `npm run test:mocha:watch`, I got an error:

```bash
> webpack-starter@0.0.0 test:mocha:watch C:\repo\webpack-starter
> webpack-dev-server --hot --config webpack.mocha.js

Configuration file found but no entry configured.
```

**Comment by bebraw** [comment]
Hi,

Can you link to a repository for me to study?

**Comment by Aladdin-ADD** [comment]
https://github.com/Aladdin-ADD/webpack-starter/tree/bug-repro

**Comment by bebraw** [comment]
I think I got it... webpack-dev-server expects an `entry` in webpack configuration (stated in the message :) ). If you want watch mode for Mocha, you could try `npm run test:mocha -- --watch`. That works for me. You can push that behind `test:mocha:watch` if you want.

Sorry for the delay, it has been busy times for me.

**Comment by Aladdin-ADD** [comment]
it works for me! thanks~

do you mind if I add `npm run test:mocha -- --watch` in the book? since some readers may missed it and got this error.

**Comment by Aladdin-ADD** [comment]
But I got confused by `test:mocha:watch`, how can I run this script?

**Comment by bebraw** [comment]
@Aladdin-ADD I see the real problem now. See [here](https://github.com/tplss/webpack-starter/blob/bug-repro/webpack.parts.js#L236) and compare to [mine](https://github.com/survivejs-demos/webpack-demo/blob/master/webpack.parts.js#L222). I inject `entry` to the configuration there. This was the real issue.

Mentioning `--watch` option could be worthwhile so let's leave this open till I have time to fix that.

**Comment by Aladdin-ADD** [comment]
hmm...seems like it's because I missed this step[04_multiple_pages.md#adjusting-configuration](https://github.com/survivejs/webpack-book/blob/dev/manuscript/output/04_multiple_pages.md#adjusting-configuration).

thanks so much!!!❤️
