### ISSUE TITLE
Enhance section on Hot Module Replacement

### ISSUE THREAD

**Issue by gavinorland** [survivejs/webpack-book#289]
I found the first half of [this section](https://survivejs.com/webpack/appendices/hmr/) to be fine, describing the need to either enable flag `--hot` or use `HotModuleReplacementPlugin()`, but in order actually get this working with React I found myself looking around for other info.

The thing that actually got it working for me was [`react-hot-loader`](https://github.com/gaearon/react-hot-loader/) so this might be specifically worth mentioning as perhaps the easiest way currently with Webpack and WDS. I also noted that only the root components needs exporting using this, _not_ each component.

The second thing I learned which might be worth including is that if not using WDS, but maybe only Express, you can enable your hot module reloading [via middleware](https://github.com/glenjamin/webpack-hot-middleware).

**Comment by sapegin** [comment]
There are two different thing: webpack hot module replacement is generic and works with any code, React Hot Loaders (and similar tools) works only with React. I’d not recommend it though and none of them are actively maintained. Most likely you don’t even need it ;-)

**Comment by gavinorland** [comment]
Thanks - I already understand those points. When you say React Hot Loader is not actively maintained, however, I am confused since a new version is being prepared [here](https://github.com/gaearon/react-hot-loader/tree/next)!

**Comment by sapegin** [comment]
Yeah, since 18 days ago ;-) But I don’t think it would change much.

**Comment by gavinorland** [comment]
It probably doesn't need to ;-)

**Comment by sapegin** [comment]
Sure, `module.hot` is enough most of the time and easy to set up ;-)

**Comment by gavinorland** [comment]
Anyway, this post is really just for Juho to consider mentioning these techniques for HMR which are also available. Thanks for your input all the same :)

**Comment by bebraw** [comment]
See https://survivejs.com/webpack/appendices/hmr/ . I added a small bit about JS and the need for *react-hot-loader* and such. It's enough that the appendix explains the webpack side of things. App-side is documented per solution.
