### ISSUE TITLE
Purifying CSS when using React

### ISSUE THREAD

**Issue by gavinorland** [survivejs/webpack-book#290]
Re. [this section](https://survivejs.com/webpack/styling/eliminating-unused-css/), as mentioned to Juho privately, I found that using PurifyCSS with a React app didn't work as expected - it stripped out too much CSS - perhaps all except that imported by the root component.

This probably won't make a difference to me as I'm going to try Styled Components, but just FYI.

**Comment by bebraw** [comment]
I've updated the chapter to purgecss (in `dev`). Not much else to do here. 👍
