### ISSUE TITLE
webpack 4

### ISSUE THREAD

**Issue by dhruvdutt** [survivejs/webpack-book#296]
webpack 4.0.0 has just [released](https://github.com/webpack/webpack/releases/tag/v4.0.0) today :fire: :rocket: 

We should consider upgrading this book to it.

Here are some of the references:

- [webpack offical docs](https://webpack.js.org/) (not completely ready for webpack 4)
- [webpack 4: release post](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4)
- [webpack 4: import() and CommonJs](https://medium.com/webpack/webpack-4-import-and-commonjs-d619d626b655)
- [webpack 4: mode and optimization](https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a)
- [webpack 4: migration guide for plugins/loaders](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202)

**Comment by bebraw** [comment]
Thanks for the heads up. I'll try to get the book up to date this week. Perhaps most importantly I can eliminate some content.

**Comment by tomByrer** [comment]
Seems WP4 is faster.  Bonus: some user bugs revealed here also:

https://twitter.com/TheLarkInn/status/964607133495865351

**Comment by bebraw** [comment]
Yeah, it's a little buggy release. 😐 

I tried updating my static site generator to use the new version and I ran into a showstopper bug. Basically the UMD output is broken for Node for now. Also extract-text-webpack-plugin isn't stable yet.

That said, I can begin upgrading the book despite these caveats. I have to wait for webpack to become more stable before pushing out a paper version, though. The initial version is also missing first class support for CSS (old workflow for now).

**Comment by dhruvdutt** [comment]
> Yeah, it's a little buggy release.

True. webpack 4 and the whole plugins ecosystem will get stable eventually but the core APIs won't change majorly AFAIK. We can begin with the book and get initial reviews till everything gets stable.

> Also extract-text-webpack-plugin isn't stable yet.

Did you try [`extract-text-webpack-plugin`@next](https://github.com/webpack-contrib/extract-text-webpack-plugin/tree/next)

**Comment by bebraw** [comment]
@dhruvdutt I think I will have to point the book to the `next` version, yeah. Also html-webpack-plugin is in bit of a flux at the moment so that's another one that requires a special note.

**Comment by bebraw** [comment]
You can follow the progress [here](https://github.com/survivejs/webpack-book/tree/webpack-4). Going well so far. This will simplify the book somewhat.

**Comment by bebraw** [comment]
FYI, a published a webpack 4 version of the book silently (both online and Leanpub). I'll hone it further this week and do a more public release.

**Comment by dhruvdutt** [comment]
Awesome, @bebraw. That was quick. :rocket:
