### ISSUE TITLE
extract-text-webpack-plugin doesn't extract a file

### ISSUE THREAD

**Issue by patrickclancy** [survivejs/webpack-book#309]
I purchased the book and I'm following the book. I'm running webpack 4.8.1, wepack-cli 2.1.3 and extract-text-webpack-plugin next. If I build the sample code I never get the extracted file or an error. I've copied and pasted the code from the book. Is extract-text-webpack-plugin next still the recommended way to extract styles?

**Comment by bebraw** [comment]
Hi Patrick,

I updated the book to use mini-css-extract-plugin a couple of days ago. It
was a silent update so make sure to download the current version. :)

**Comment by patrickclancy** [comment]
oh... awesome! Thanks for the super quick response
