### ISSUE TITLE
building - tidying up - CleanWebpackPlugin@3.0.0 replace default export with named export

### ISSUE THREAD

**Issue by liuzhuan** [survivejs/webpack-book#317]
If we install the latest `clean-webpack-plugin`, which is v3.0.0 now. And we require its default export, such as:

```js
const CleanWebpackPlugin = require("clean-webpack-plugin");
```

We would get a error:

```sh
TypeError: HtmlWebpackPlugin is not a constructor
...
```

Because the default export has been replaced with named export in [this commit](https://github.com/johnagan/clean-webpack-plugin/commit/d0e34084e20f0a0f0857d117d665f5ee8536dfa5).

So we should change the require method a little, just for v3.0.0+:

```js
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
```

**Comment by bebraw** [comment]
Thanks, I'll fix for the next revision.

**Comment by bebraw** [comment]
Done at `dev`. Sorry for the delay!
