### ISSUE TITLE
Feed back and suggestions

### ISSUE THREAD

**Issue by cdoublev** [survivejs/webpack-book#331]
Hello,

I hadn't read this book for a long time. I needed to refresh my memory on a specific point, and I thought that reading it (almost) entirely from the beginning might allow me to thank you by giving you back the following feed backs / suggestions.

---

- [x] **Add multimedia files to the list of files consumed by web browsers**

**Page:** Introduction #L9
**Suggested change:**

```diff
- Web browsers consume HTML, CSS, and JavaScript. [...]
+ Web browsers consume HTML, CSS, JavaScript, and mutlimedia files. [...]
```

**Why?** Images (and eventually other embedded files such as video/audio) are also resources that browsers will consume and that Webpack (plugins) can bundle/optimize.

---

- [x] **Define *"configuring a file"***

**Page:** Introduction #L9
**Suggested change:**

```diff
- [...] As a project grows, tracking and configuring all of these files becomes too complicated to manage without help.
+ [...] As a project grows, tracking all of these files and adapting them to different targets (eg. browsers) becomes too complicated to manage without help.
```

**Why?** This is a subjective change since I couldn't understand what *"configuring a file"* means, even with my good experience with Webpack.

---

- [x] **Define *"last bundle"***

**Page:** What is Webpack #L57
**Suggested change:**

```diff
- If loader evaluation completed without a runtime error, webpack includes the source in the last bundle.
+ If loader evaluation completed without a runtime error, webpack includes the source in the bundle.
```

**Why?** I'm not sure what a *"last bundle"* means. Is it the last chunk? Or the last bundle when using a multi-compiler configuration? In both cases, isn't it too early to talk about multiple bundles?

---

- [x] **Remove repetition (*"plugins allow you to intercept runtime events"*)**

**Page:** What is Webpack #L57-59
**Suggested change:**

```diff
- If loader evaluation completed without a runtime error, webpack includes the source in the last bundle. **Plugins** allow you to intercept **runtime events** at different stages of the bundling process.
- 
- Although loaders can do a lot, they don't provide enough power for advanced tasks. Plugins can intercept **runtime events** supplied by webpack. 
+ If loader evaluation completed without a runtime error, webpack includes the source in the last bundle.
+ 
+ Although loaders can do a lot, they don't provide enough power for advanced tasks. Plugins can intercept **runtime events** supplied by webpack at different stages of the bundling process. 
```

---

- [x] **Clearly define who is responsible for loading resources (bootstrap/runtime/manifest)**

**Page:** What is Webpack #L63
**Suggested change:**

```diff
- [...] The output includes a bootstrap script with a manifest that describes how to begin executing the result in the browser.
+ [...] The output includes a bootstrap: a runtime script to execute the result in a browser, and a manifest to help doing this.
```

**Why?** I feel like there's some general confusion around those terms: *"bootstrap"*, *"runtime"*, and *"manifest"*. To me, the bootstrap contains the runtime script and the manifest. The manifest is essentially text data (in JS comments or a JSON tree) that maps source and distributed file paths, plus extra information. But it can't execute anything, contrary to what this sentence is meaning.

---

- [x] **Set a different output path/filename than the entry path/filename**

**Page:** What is Webpack #L88
**Suggested change:**

```diff
-    filename: "[name].js",
+    filename: "[name].bundled.js",
```

**Why?** I believe that the source (entry) file will be erased when using this configuration.

---

- [x] **Be more specific about what OS/solutions are problematic with file watching**

**Page:** Developing / Development server #L164
**Suggested change:**

```diff
- It can be problematic on older versions of Windows, Ubuntu, Vagrant, and Docker.
+ It can be problematic on older versions of Windows and Ubuntu, and is almost mandatory when using Vagrant, Docker, or any other solution that doesn't forward events for changes on a file located in a folder shared with the virtualized machine where Webpack is running.
```

**Why?** I don't know about file watching issues on Windows/Ubuntu, but I use Vagrant on Windows since many years and I believe that polling is mandatory. There's [`vagrant-notify-forwarder`](https://github.com/mhallin/vagrant-notify-forwarder) but only for MacOS/Unix.

---

- [x] **Use `watchOptions.ignored` instead of `webpack.WatchIgnorePlugin`**

**Page:** Developing / Development server #L172-189
**Suggested change:**

```diff
 module.exports = {
    devServer: {
      watchOptions: {
        // Delay the rebuild after the first change
        aggregateTimeout: 300,
  
        // Poll using interval (in ms, accepts boolean too)
        poll: 1000,
+       ignored: /node_modules/
      },
    },
-   plugins: [
-     // Ignore node_modules so CPU usage with poll
-     // watching drops significantly.
-     new webpack.WatchIgnorePlugin([
-       path.join(__dirname, "node_modules"),
-     ]),
-   ],
};
```

**Why?** This looks like a simpler alternative ([documentation](https://webpack.js.org/configuration/watch/#watchoptionsignored)).

---

- [x] **Add a note about build performance when using a single configuration file containing all parts (+ rewording)**

**Page:** Developing / Composing configuration #L208
**Suggested change:**

```diff
- This arrangement would make it faster to find configuration related to a category. A good option would be to arrange the parts within a single file and use comments to split it up.
+ This arrangement would make it faster to find configuration related to a category, and can also reduce your build time if you're consuming parts from a published package (only the required plugins will have to be loaded). A good alternative for better readability would be to arrange the parts within a single file and use comments to split it up.
};
```

**Why?** Only the required plugins will have to be loaded when using separate file for each part.

---

- [x] **Rewording to remove *"and"* repetitions**

**Page:** Styling / Loading #L46
**Suggested change:**

```diff
- Loaders are transformations that are applied to source files, and return the new source and can be chained together like a pipe in Unix. They are evaluated from right to left.
+ Loaders return the new source files with transformations applied on them. They can be chained together like a pipe in Unix, and are evaluated from right to left.
};
```

---

- [x] **Distinguish rendering from loading inline style**

**Page:** Styling / Separating CSS #L9
**Suggested change:**

```diff
- It can be potentially dangerous to use inline styles within JavaScript in production as it represents an attack vector. **Critical path rendering** embraces the idea and inlines the critical CSS to the initial HTML payload improving the perceived performance of the site. [...]
+ It can be potentially dangerous to load inline styles with JavaScript in production, as it represents an attack vector. **Critical path rendering** embraces the idea of rendering the critical CSS with inline styles in the initial HTML payload, improving the perceived performance of the site. [...]
};
```

**Why?** I think it's not clear that inlining style server side doesn't represent a securtiy threat. My first understanding was that *critical path rendering embraces the idea of being potentially dangerous*.

---

- [x] **Add a note about automatic inclusion of `core-js` modules with Babel `useBuiltIns` `usage` or `entry`**

**Page:** Loading / JavaScript #L160
**Suggested change:**

```diff
- You have to include **core-js** to your project either through an import or an entry (`app: ["core-js", PATHS.app]`). [...]
+ You have to include **core-js** to your project either through an import or an entry (`app: ["core-js", PATHS.app]`), except if you're using `useBuiltIns: 'usage'` to configure `@babel/preset-env`. [...]
};
```

**Why?** I'm not sure about `useBuiltIns: 'entry'` but I'm currently using `useBuiltIns: 'usage'` by default in a few packages, where required `core-js` imports are automatically added by Babel. Quoting a [Babel blog post](https://babeljs.io/blog/2018/08/27/7.0.0): *It will run through each file and inject an import at the top of each file if that built-in is "used" in the code.* And [`@babel/preset-env` documentation](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage) : *Adds specific imports for polyfills when they are used in each file.*

---

- [x] **Be more specific about when both `NODE_ENV` and `BABEL_ENV` are set**

**Page:** Loading / JavaScript #L199
**Suggested change:**

```diff
- [...] If `BABEL_ENV` is set, it overrides any possible `NODE_ENV`.
+ [...] If both `BABEL_ENV` and `NODE_ENV` are set, the former takes precedence to resolve `env`.
};
```

**Why?** Not verified, but it would make sense.

**Comment by bebraw** [comment]
@cdoublev Awesome, thanks a lot! I'm currently working on a new revision of the book (see the `dev` branch). I'll make sure to get your proposed changes in.

**Comment by cdoublev** [comment]
Indeed I read the online version before noticing your recent revisions, after cloning this repository. Obviously I had to remove some of my initial suggestions after reading it a second time (in vscode).

**Comment by bebraw** [comment]
Thanks a lot again! I've applied the fixes and rewritten a bit where needed.

Regarding `filename: "[name].js",`, that's going to pick up the key from the `entry` since we're using an object there. The whole entry configuration portion might deserve specific discussion somewhere as it has become amazingly flexible and it supports a lot of different types of usages these days.
