### ISSUE TITLE
WebSocket connection to 'ws://[::]:8080/wps' failed

### ISSUE THREAD

**Issue by heart-er** [survivejs/webpack-book#342]
When i use Webpack-Plugin-Serve and npm start
![image](https://user-images.githubusercontent.com/24717511/105724237-9c617b00-5f62-11eb-9bb1-98f09da3d5bb.png)

source code:
![image](https://user-images.githubusercontent.com/24717511/105724293-a8e5d380-5f62-11eb-829d-e6f0e034558c.png)
![image](https://user-images.githubusercontent.com/24717511/105724319-af744b00-5f62-11eb-8ed2-29e637db648e.png)

**Comment by bebraw** [comment]
How did you solve it? 😄

**Comment by leakko** [comment]
I have the same problem...
