### ISSUE TITLE
in safari, not passing host fails the live reload of code

### ISSUE THREAD

**Issue by superandrew** [survivejs/webpack-book#343]
In the book the example with webpack-plugin-serve fails on Safari (Mac Os Big sure) unless host is specified:

```
module.exports = {
  watch: mode === "development",
  entry: ["./src", "webpack-plugin-serve/client"],
  mode,
  plugins: [
    new MiniHtmlWebpackPlugin({ context: { title: "Demo" } }),
    new WebpackPluginServe({
      port: process.env.PORT || 8080,
      static: "./dist",
      liveReload: true,
      waitForBuild: true,
      host: "127.0.0.1",
    }),
  ],
}
```

In chrome it works normally. It took some time to understand what was going wrong, so I hope this might help others.

**Comment by superandrew** [comment]
I think it's related to https://github.com/survivejs/webpack-book/issues/342 (not sure why it was closed by the OP)

**Comment by bebraw** [comment]
Thanks! I've fixed this and I'll deploy the fix soon.

I opened a related issue at https://github.com/shellscape/webpack-plugin-serve/issues/215 . Maybe you can comment there.
