### ISSUE TITLE
dynamic import about terser error

### ISSUE THREAD

**Issue by heart-er** [survivejs/webpack-book#344]
when i add dynamic import in component.js
![image](https://user-images.githubusercontent.com/24717511/109666167-e7962b80-7ba9-11eb-991b-fecd21c25453.png)

it throws error
![image](https://user-images.githubusercontent.com/24717511/109666287-03013680-7baa-11eb-94aa-870488b7651f.png)

**Comment by bebraw** [comment]
Can you push your project to GitHub so I can have a closer look? It feels like something in Babel configuration.

I have a reference implementation at https://github.com/survivejs-demos/webpack-demo .

**Comment by heart-er** [comment]
Yes, when I added the "targets: { "esmodules": true } "in the babel file, the error disappeared
![image](https://user-images.githubusercontent.com/24717511/109674186-adc92300-7bb1-11eb-98d8-e00772e35561.png)

**Comment by heart-er** [comment]
https://github.com/babel/babel/issues/9849

**Comment by heart-er** [comment]
webpack version is 5.24.2

**Comment by heart-er** [comment]
https://github.com/heart-er/test-webpack

This is my webpack, please help me to check if I can remove target modules in babel

**Comment by bebraw** [comment]
I know `"modules": false` is important for webpack but the `targets` bit is new to me. I wonder if something has changed there in the past months. Let me verify and get back to you latest tomorrow.

**Comment by bebraw** [comment]
I tried out your project. If I reduce the configuration to the following it still works:

```json
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": false
            }
        ]
    ]
}
```

That `"modules": false` bit is crucial as otherwise webpack won't be able to use tree shaking properly.

Can you push code that's leading to the error in your repository?

**Comment by heart-er** [comment]
The development environment is fine, but is you execute npm run build, it will throw an error.

**Comment by heart-er** [comment]
you can remove target within my repository and excute npm run build.

**Comment by bebraw** [comment]
Ok, I see now. I can reproduce the issue if I empty your `.browserslistrc`.

The problem has to do with Terser and its capabilities in minifying the code. It's crashing as it cannot deal with the syntax. It can be something as simple as a trailing comma.

Here's more information: https://github.com/webpack-contrib/terser-webpack-plugin/issues/114 . It's possible setting the `ecma` option to 8 at terser options (see the minifying chapter) could resolve the issue if you want to compile for the most modern browsers only (I assume removing targets from browserslistrc is doing this exactly).

**Comment by heart-er** [comment]
So, if I remove the target, it needs to be compatible with the old browser, what should I do?

**Comment by bebraw** [comment]
Which browsers do you want to target?

**Comment by heart-er** [comment]
> Which browsers do you want to target?
> […](#)
> On 03.03.2021, at 12:08, heart ***@***.***> wrote: ﻿ So, if I remove the target, it needs to be compatible with the old browser, what should I do? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

IE 10 +

**Comment by bebraw** [comment]
Ok, in that case it's enough to set `.browserslistrc` like this:

```
IE >= 10
```

I checked with your build command and it compiles now with this.

**Comment by heart-er** [comment]
Thank you very much!

**Comment by bebraw** [comment]
Cool, let's close?

**Comment by heart-er** [comment]
Ok
