### ISSUE TITLE
"watch" script throwing an error

### ISSUE THREAD

**Issue by duty-bound** [survivejs/webpack-book#347]
I am currently on Chapter 3: Composing Configuration.

When running the below script I get an error:
```
"watch": "nodemon --watch webpack.* --exec \"npm run start\"",
```
Error:
![chp3](https://user-images.githubusercontent.com/38318301/118407227-1176ce80-b680-11eb-944b-a9284ca95c31.png)

If I rename "webpack.parts.js" to "parts.js" (and obviously update the respective 'require' statement in 'webpack.config.js) everything works fine; however "parts.js" will no longer be watched for changes.

Is it me doing something wrong or does this script need to be amended please?

Code available in this repo [here](https://github.com/duty-bound/webpack5-a2m).

**Comment by bebraw** [comment]
Hi,

Can you change to `"watch": "nodemon --watch \"./webpack.*\" --exec \"npm run start\"",`? Note the escaping I added.

I'll have to change this in the book as well so please don't close the issue until I do so. 👍

**Comment by duty-bound** [comment]
Thanks for your solution :)

**Comment by rjvim** [comment]
For some reason above one doesn't work for me:

I have to change to:

```
    "watch": "nodemon --watch \"./webpack.*.*\" --exec \"npm start\"",
```

Notice: `webpack.*.*`, even changing to `webpack.config.js` works, but not just `webpack.*`

**Comment by bebraw** [comment]
@rjvim Thanks for the heads up. It's possible nodemon is more strict about `*` now so I adjusted the book accordingly.
