### ISSUE TITLE
Chapter - Testing

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack-book#87]
Basic setups. Karma+Mocha+???, testem, others? Please comment what you would like to see there.

**Comment by alejandronanez** [comment]
I'd like to see something related to AVA or maybe Karma+Mocha (it's way more popular).
+ Something about coverage.

**Comment by QuantumInformation** [comment]
Karma + mocha would be great.

**Comment by sapegin** [comment]
Jest!

**Comment by drawm** [comment]
+1 Karma+Mocha

**Comment by jeggett** [comment]
Jest

**Comment by klauszhang** [comment]
karmar+mocha+coverage (getting coverage of transpiled code, such as typescript )

**Comment by davidmoshal** [comment]
typescript, wallabyjs

**Comment by bebraw** [comment]
There's a chapter to preview now, https://github.com/survivejs/webpack-book/blob/dev/manuscript/techniques/04_testing.md .
